# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addFunc.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_addFuc(object):
    def setupUi(self, Form_addFuc):
        Form_addFuc.setObjectName("Form_addFuc")
        Form_addFuc.resize(337, 212)
        Form_addFuc.setWindowTitle("Novo cadastro")
        Form_addFuc.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_addFuc = QtWidgets.QPushButton(Form_addFuc)
        self.pushButton_addFuc.setGeometry(QtCore.QRect(10, 180, 141, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_addFuc.setFont(font)
        self.pushButton_addFuc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_addFuc.setObjectName("pushButton_addFuc")
        self.pushButton_voltar = QtWidgets.QPushButton(Form_addFuc)
        self.pushButton_voltar.setGeometry(QtCore.QRect(250, 180, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.label = QtWidgets.QLabel(Form_addFuc)
        self.label.setGeometry(QtCore.QRect(10, 20, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_addFuc)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_addFuc)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form_addFuc)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setObjectName("label_4")
        self.lineEdit_salario = QtWidgets.QLineEdit(Form_addFuc)
        self.lineEdit_salario.setGeometry(QtCore.QRect(70, 140, 261, 20))
        self.lineEdit_salario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_salario.setObjectName("lineEdit_salario")
        self.lineEdit_cargo = QtWidgets.QLineEdit(Form_addFuc)
        self.lineEdit_cargo.setGeometry(QtCore.QRect(70, 100, 261, 20))
        self.lineEdit_cargo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_cargo.setObjectName("lineEdit_cargo")
        self.lineEdit_cpf = QtWidgets.QLineEdit(Form_addFuc)
        self.lineEdit_cpf.setGeometry(QtCore.QRect(70, 60, 261, 20))
        self.lineEdit_cpf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_cpf.setObjectName("lineEdit_cpf")
        self.lineEdit_Nome = QtWidgets.QLineEdit(Form_addFuc)
        self.lineEdit_Nome.setGeometry(QtCore.QRect(70, 20, 261, 20))
        self.lineEdit_Nome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nome.setObjectName("lineEdit_Nome")

        self.retranslateUi(Form_addFuc)
        QtCore.QMetaObject.connectSlotsByName(Form_addFuc)

    def retranslateUi(self, Form_addFuc):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_addFuc.setText(_translate("Form_addFuc", "Adicionar Funcionário"))
        self.pushButton_voltar.setText(_translate("Form_addFuc", "Voltar"))
        self.label.setText(_translate("Form_addFuc", "Nome:"))
        self.label_2.setText(_translate("Form_addFuc", "CPF:"))
        self.label_3.setText(_translate("Form_addFuc", "Cargo:"))
        self.label_4.setText(_translate("Form_addFuc", "Salário:"))