# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(503, 365)
        Form.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setMidLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_Nome = QtWidgets.QLabel(Form)
        self.label_Nome.setGeometry(QtCore.QRect(180, 20, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Nome.setFont(font)
        self.label_Nome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Nome.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Nome.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_Nome.setMidLineWidth(0)
        self.label_Nome.setText("")
        self.label_Nome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Nome.setObjectName("label_Nome")
        self.label_CPF = QtWidgets.QLabel(Form)
        self.label_CPF.setGeometry(QtCore.QRect(180, 60, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_CPF.setFont(font)
        self.label_CPF.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_CPF.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_CPF.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_CPF.setMidLineWidth(0)
        self.label_CPF.setText("")
        self.label_CPF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_CPF.setObjectName("label_CPF")
        self.label_Cargo = QtWidgets.QLabel(Form)
        self.label_Cargo.setGeometry(QtCore.QRect(180, 100, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Cargo.setFont(font)
        self.label_Cargo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Cargo.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Cargo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_Cargo.setMidLineWidth(0)
        self.label_Cargo.setText("")
        self.label_Cargo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Cargo.setObjectName("label_Cargo")
        self.label_Salario = QtWidgets.QLabel(Form)
        self.label_Salario.setGeometry(QtCore.QRect(180, 140, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_Salario.setFont(font)
        self.label_Salario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Salario.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Salario.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_Salario.setMidLineWidth(0)
        self.label_Salario.setText("")
        self.label_Salario.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Salario.setObjectName("label_Salario")
        self.label_HoraExtra = QtWidgets.QLabel(Form)
        self.label_HoraExtra.setGeometry(QtCore.QRect(180, 180, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_HoraExtra.setFont(font)
        self.label_HoraExtra.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_HoraExtra.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_HoraExtra.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_HoraExtra.setMidLineWidth(0)
        self.label_HoraExtra.setText("")
        self.label_HoraExtra.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_HoraExtra.setObjectName("label_HoraExtra")
        self.lineEdit_HoraExtra = QtWidgets.QLineEdit(Form)
        self.lineEdit_HoraExtra.setGeometry(QtCore.QRect(390, 280, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_HoraExtra.setFont(font)
        self.lineEdit_HoraExtra.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_HoraExtra.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_HoraExtra.setObjectName("lineEdit_HoraExtra")
        self.pushButton_InsereHE = QtWidgets.QPushButton(Form)
        self.pushButton_InsereHE.setGeometry(QtCore.QRect(290, 310, 171, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_InsereHE.setFont(font)
        self.pushButton_InsereHE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_InsereHE.setObjectName("pushButton_InsereHE")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(290, 280, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_12.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_12.setMidLineWidth(0)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_PagExtra = QtWidgets.QLabel(Form)
        self.label_PagExtra.setGeometry(QtCore.QRect(180, 220, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_PagExtra.setFont(font)
        self.label_PagExtra.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_PagExtra.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_PagExtra.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_PagExtra.setMidLineWidth(0)
        self.label_PagExtra.setText("")
        self.label_PagExtra.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_PagExtra.setObjectName("label_PagExtra")
        self.lineEdit_Nome = QtWidgets.QLineEdit(Form)
        self.lineEdit_Nome.setGeometry(QtCore.QRect(20, 280, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Nome.setFont(font)
        self.lineEdit_Nome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Nome.setText("")
        self.lineEdit_Nome.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Nome.setObjectName("lineEdit_Nome")
        self.pushButton_Buscar = QtWidgets.QPushButton(Form)
        self.pushButton_Buscar.setGeometry(QtCore.QRect(50, 310, 171, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Buscar.setFont(font)
        self.pushButton_Buscar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_Buscar.setObjectName("pushButton_Buscar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_Nome, self.pushButton_Buscar)
        Form.setTabOrder(self.pushButton_Buscar, self.lineEdit_HoraExtra)
        Form.setTabOrder(self.lineEdit_HoraExtra, self.pushButton_InsereHE)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Nome:"))
        self.label_2.setText(_translate("Form", "CPF:"))
        self.label_3.setText(_translate("Form", "Salário:"))
        self.label_4.setText(_translate("Form", "Horas extras:"))
        self.label_5.setText(_translate("Form", "Cargo:"))
        self.pushButton_InsereHE.setText(_translate("Form", "Inserir hora extra"))
        self.label_12.setText(_translate("Form", "Hora Extra:"))
        self.label_6.setText(_translate("Form", "Pagamento extra:"))
        self.pushButton_Buscar.setText(_translate("Form", "Buscar por nome"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
