import my_doc
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

alunos = list()

####Funçao que fecha tudo#######

def fechar_tudo():
    Menu_Main.close()
    Menu_NT.close()
    Menu_CT.close()
    visualizar_aluno.close()
    cadastro_aluno.close()

#######Janelas a serem chamadas#########

def Window_VD():
    fechar_tudo()
    visualizar_aluno.show()

def Window_CD():
    fechar_tudo()
    cadastro_aluno.show()

def Window_NT():
    fechar_tudo()
    Menu_NT.show()

def Window_CT():
    fechar_tudo()
    Menu_CT.show()

def Window_MM():
    fechar_tudo()
    Menu_Main.show()

#######Função dos botões####

def criar_turma():
    nome = ui_NT.lineEdit_NomeNT.text()
    my_doc.criar_txt(nome)
    Window_MM()

def carregar_turma():
    nome = ui_CT.lineEdit_NomeNT.text()
    global alunos
    alunos = my_doc.ler_txt(nome, ['Nome', 'Matricula', 'Idade', 'IC', 'IP', 'MD', 'CI', 'AVL'])
    Window_MM()

def visu_aluno():
    matricula = ui_VD.lineEdit_FindMatric.text()
    aluno = my_doc.find_aluno(matricula, alunos) ##vai receber o dicionário do aluno
    ui_VD.Label_SetNome.setText(aluno['Nome'])
    ui_VD.Label_SetMatricula.setText(str(int(aluno['Matricula'])))
    ui_VD.Label_SetIdade.setText(str(int(aluno['Idade'])))
    ui_VD.Label_ICNota.setText(str(aluno['IC']))
    ui_VD.Label_IPNota.setText(str(aluno['IP']))
    ui_VD.Label_MDNota.setText(str(aluno['MD']))
    ui_VD.Label_CINota.setText(str(aluno['CI']))
    ui_VD.Label_AVLNota.setText(str(aluno['AVL']))

def cadas_aluno():
    infoAluno = list()
    arquivo = ui_CD.lineEdit_getTurma.text()
    infoAluno.append(ui_CD.lineEdit_getNome.text())
    infoAluno.append(ui_CD.lineEdit_getMatricula.text())
    infoAluno.append(ui_CD.lineEdit_getIdade.text())
    infoAluno.append(ui_CD.lineEdit_getICNota.text())
    infoAluno.append(ui_CD.lineEdit_getIPNota.text())
    infoAluno.append(ui_CD.lineEdit_getMDNota.text())
    infoAluno.append(ui_CD.lineEdit_getCINota.text())
    infoAluno.append(ui_CD.lineEdit_getAVLNota.text())
    my_doc.escreve_txt(arquivo, infoAluno)


###########Frames#################
class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(372, 248)
        Menu.setDocumentMode(False)
        self.Frame1 = QtWidgets.QWidget(Menu)
        self.Frame1.setObjectName("Frame1")
        self.label_inicial = QtWidgets.QLabel(self.Frame1)
        self.label_inicial.setGeometry(QtCore.QRect(50, 20, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        #-----------------------------------
        self.label_inicial.setFont(font)
        self.label_inicial.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inicial.setObjectName("label_inicial")
        #-----------------------------------
        self.pushButton_Cadastrar = QtWidgets.QPushButton(self.Frame1)
        self.pushButton_Cadastrar.setGeometry(QtCore.QRect(40, 150, 91, 41))
        self.pushButton_Cadastrar.setObjectName("pushButton_Cadastrar")
        self.pushButton_Cadastrar.clicked.connect(Window_CD)
        #-----------------------------------
        self.pushButton_Vizualizar = QtWidgets.QPushButton(self.Frame1)
        self.pushButton_Vizualizar.setGeometry(QtCore.QRect(240, 150, 91, 41))
        self.pushButton_Vizualizar.setObjectName("pushButton_Vizualizar")
        self.pushButton_Vizualizar.clicked.connect(Window_VD)
        #-----------------------------------
        Menu.setCentralWidget(self.Frame1)
        #-----------------------------------
        self.menubar = QtWidgets.QMenuBar(Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 372, 21))
        self.menubar.setObjectName("menubar")
        #-----------------------------------
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        #-----------------------------------
        Menu.setMenuBar(self.menubar)
        #-----------------------------------
        self.action_Novo = QtWidgets.QAction(Menu)
        self.action_Novo.setObjectName("action_Novo")
        self.action_Novo.triggered.connect(Window_NT)
        #-----------------------------------
        self.action_Carregar_turma = QtWidgets.QAction(Menu)
        self.action_Carregar_turma.setObjectName("action_Carregar_turma")
        self.action_Carregar_turma.triggered.connect(Window_CT)#diferente do botão
        #-----------------------------------
        self.menu_File.addAction(self.action_Novo)
        self.menu_File.addAction(self.action_Carregar_turma)
        #-----------------------------------
        self.menubar.addAction(self.menu_File.menuAction())
        #-----------------------------------
        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)
        #-----------------------------------
    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "QT-Academico"))
        self.label_inicial.setText(_translate("Menu", "BEM - VINDO"))
        self.pushButton_Cadastrar.setText(_translate("Menu", "Cadastrar"))
        self.pushButton_Vizualizar.setText(_translate("Menu", "Vizualizar"))
        self.menu_File.setTitle(_translate("Menu", "File"))
        self.action_Novo.setText(_translate("Menu", "Criar turma"))
        self.action_Carregar_turma.setText(_translate("Menu", "Carregar turma"))

class Ui_Frame_Nova_turma(object):
    def setupUi(self, Frame_Nova_turma):
        Frame_Nova_turma.setObjectName("Frame_Nova_turma")
        Frame_Nova_turma.resize(271, 116)
        self.label_titulo = QtWidgets.QLabel(Frame_Nova_turma)
        self.label_titulo.setGeometry(QtCore.QRect(0, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        #--------------------------------------------------------------
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        #--------------------------------------------------------------
        self.lineEdit_NomeNT = QtWidgets.QLineEdit(Frame_Nova_turma)
        self.lineEdit_NomeNT.setGeometry(QtCore.QRect(10, 40, 251, 21))
        self.lineEdit_NomeNT.setObjectName("lineEdit_NomeNT")
        #--------------------------------------------------------------
        self.pushButton_Criar = QtWidgets.QPushButton(Frame_Nova_turma)
        self.pushButton_Criar.setGeometry(QtCore.QRect(10, 80, 111, 23))
        self.pushButton_Criar.setObjectName("pushButton_Criar")
        self.pushButton_Criar.clicked.connect(criar_turma)
        #--------------------------------------------------------------
        self.pushButton_Voltar = QtWidgets.QPushButton(Frame_Nova_turma)
        self.pushButton_Voltar.setGeometry(QtCore.QRect(150, 80, 111, 23))
        self.pushButton_Voltar.setObjectName("pushButton_Voltar")
        self.pushButton_Voltar.clicked.connect(Window_MM)

        self.retranslateUi(Frame_Nova_turma)
        QtCore.QMetaObject.connectSlotsByName(Frame_Nova_turma)

    def retranslateUi(self, Frame_Nova_turma):
        _translate = QtCore.QCoreApplication.translate
        Frame_Nova_turma.setWindowTitle(_translate("Frame_Nova_turma", "QT-Academico"))
        self.label_titulo.setText(_translate("Frame_Nova_turma", "Digite o nome da nova turma"))
        self.pushButton_Criar.setText(_translate("Frame_Nova_turma", "Criar"))
        self.pushButton_Voltar.setText(_translate("Frame_Nova_turma", "Voltar"))

class Ui_Frame_carregar_turma(object):
    def setupUi(self, Frame_carregar_turma):
        Frame_carregar_turma.setObjectName("Frame_carregar_turma")
        Frame_carregar_turma.resize(271, 116)
        self.label_titulo = QtWidgets.QLabel(Frame_carregar_turma)
        self.label_titulo.setGeometry(QtCore.QRect(0, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        #--------------------------------------------------------------
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        #--------------------------------------------------------------
        self.lineEdit_NomeNT = QtWidgets.QLineEdit(Frame_carregar_turma)
        self.lineEdit_NomeNT.setGeometry(QtCore.QRect(10, 40, 251, 21))
        self.lineEdit_NomeNT.setObjectName("lineEdit_NomeNT")
        #--------------------------------------------------------------
        self.pushButton_carregar = QtWidgets.QPushButton(Frame_carregar_turma)
        self.pushButton_carregar.setGeometry(QtCore.QRect(10, 80, 111, 23))
        self.pushButton_carregar.setObjectName("pushButton_carregar")
        self.pushButton_carregar.clicked.connect(carregar_turma)
        #--------------------------------------------------------------
        self.pushButton_Voltar = QtWidgets.QPushButton(Frame_carregar_turma)
        self.pushButton_Voltar.setGeometry(QtCore.QRect(150, 80, 111, 23))
        self.pushButton_Voltar.setObjectName("pushButton_Voltar")
        self.pushButton_Voltar.clicked.connect(Window_MM)

        self.retranslateUi(Frame_carregar_turma)
        QtCore.QMetaObject.connectSlotsByName(Frame_carregar_turma)

    def retranslateUi(self, Frame_carregar_turma):
        _translate = QtCore.QCoreApplication.translate
        Frame_carregar_turma.setWindowTitle(_translate("Frame_carregar_turma", "QT-Academico"))
        self.label_titulo.setText(_translate("Frame_carregar_turma", "Digite o nome da Turma"))
        self.pushButton_carregar.setText(_translate("Frame_carregar_turma", "carregar"))
        self.pushButton_Voltar.setText(_translate("Frame_carregar_turma", "Voltar"))

class Ui_visualizar_aluno(object):##
    def setupUi(self, visualizar_aluno):
        visualizar_aluno.setObjectName("visualizar_aluno")
        visualizar_aluno.resize(447, 486)
        #-------------------------------------------------------------------
        self.pushButton_procurar = QtWidgets.QPushButton(visualizar_aluno)
        self.pushButton_procurar.setGeometry(QtCore.QRect(20, 440, 75, 23))
        self.pushButton_procurar.setObjectName("pushButton_procurar")
        self.pushButton_procurar.clicked.connect(visu_aluno)
        #-------------------------------------------------------------------
        self.pushButton_voltar = QtWidgets.QPushButton(visualizar_aluno)
        self.pushButton_voltar.setGeometry(QtCore.QRect(340, 440, 75, 23))
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.pushButton_voltar.clicked.connect(Window_MM)
        #-------------------------------------------------------------------
        self.label = QtWidgets.QLabel(visualizar_aluno)
        self.label.setGeometry(QtCore.QRect(80, 40, 91, 41))
        self.label.setObjectName("label")
        #-------------------------------------------------------------------
        self.lineEdit_FindMatric = QtWidgets.QLineEdit(visualizar_aluno)
        self.lineEdit_FindMatric.setGeometry(QtCore.QRect(180, 50, 211, 21))
        self.lineEdit_FindMatric.setObjectName("lineEdit_FindMatric")
        #-------------------------------------------------------------------
        self.groupBox = QtWidgets.QGroupBox(visualizar_aluno)
        self.groupBox.setGeometry(QtCore.QRect(80, 100, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_4.setObjectName("label_4")
        #-------------------------------------------------------------------
        self.Label_SetMatricula = QtWidgets.QLabel(self.groupBox)
        self.Label_SetMatricula.setGeometry(QtCore.QRect(110, 60, 171, 16))
        #-------------------------------------------------------------------
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        #-------------------------------------------------------------------
        self.Label_SetMatricula.setFont(font)
        self.Label_SetMatricula.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Label_SetMatricula.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Label_SetMatricula.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_SetMatricula.setObjectName("Label_SetMatricula")
        #-------------------------------------------------------------------
        self.Label_SetNome = QtWidgets.QLabel(self.groupBox)
        self.Label_SetNome.setGeometry(QtCore.QRect(110, 30, 171, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Label_SetNome.setFont(font)
        self.Label_SetNome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Label_SetNome.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Label_SetNome.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_SetNome.setObjectName("Label_SetNome")
        #-------------------------------------------------------------------
        self.Label_SetIdade = QtWidgets.QLabel(self.groupBox)
        self.Label_SetIdade.setGeometry(QtCore.QRect(110, 90, 171, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Label_SetIdade.setFont(font)
        self.Label_SetIdade.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Label_SetIdade.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Label_SetIdade.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_SetIdade.setObjectName("Label_SetIdade")
        #-------------------------------------------------------------------
        self.groupBox_2 = QtWidgets.QGroupBox(visualizar_aluno)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 220, 311, 191))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 171, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 171, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 171, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 171, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 150, 171, 16))
        self.label_9.setObjectName("label_9")
        #-------------------------------------------------------------------
        self.Label_ICNota = QtWidgets.QLabel(self.groupBox_2)
        self.Label_ICNota.setGeometry(QtCore.QRect(220, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.Label_ICNota.setFont(font)
        self.Label_ICNota.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "selection-color: rgb(0, 0, 0);")
        self.Label_ICNota.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Label_ICNota.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_ICNota.setLineWidth(1)
        self.Label_ICNota.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_ICNota.setObjectName("Label_ICNota")
        #-------------------------------------------------------------------
        self.Label_IPNota = QtWidgets.QLabel(self.groupBox_2)
        self.Label_IPNota.setGeometry(QtCore.QRect(220, 60, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.Label_IPNota.setFont(font)
        self.Label_IPNota.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "selection-color: rgb(0, 0, 0);")
        self.Label_IPNota.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Label_IPNota.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_IPNota.setLineWidth(1)
        self.Label_IPNota.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_IPNota.setObjectName("Label_IPNota")
        #-------------------------------------------------------------------
        self.Label_MDNota = QtWidgets.QLabel(self.groupBox_2)
        self.Label_MDNota.setGeometry(QtCore.QRect(220, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.Label_MDNota.setFont(font)
        self.Label_MDNota.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "selection-color: rgb(0, 0, 0);")
        self.Label_MDNota.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Label_MDNota.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_MDNota.setLineWidth(1)
        self.Label_MDNota.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_MDNota.setObjectName("Label_MDNota")
        #-------------------------------------------------------------------
        self.Label_CINota = QtWidgets.QLabel(self.groupBox_2)
        self.Label_CINota.setGeometry(QtCore.QRect(220, 120, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.Label_CINota.setFont(font)
        self.Label_CINota.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "selection-color: rgb(0, 0, 0);")
        self.Label_CINota.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Label_CINota.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_CINota.setLineWidth(1)
        self.Label_CINota.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_CINota.setObjectName("Label_CINota")
        #-------------------------------------------------------------------
        self.Label_AVLNota = QtWidgets.QLabel(self.groupBox_2)
        self.Label_AVLNota.setGeometry(QtCore.QRect(220, 150, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.Label_AVLNota.setFont(font)
        self.Label_AVLNota.setStyleSheet("background-color: rgb(255, 255, 255);\n"
        "selection-color: rgb(0, 0, 0);")
        self.Label_AVLNota.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Label_AVLNota.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_AVLNota.setLineWidth(1)
        self.Label_AVLNota.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_AVLNota.setObjectName("Label_AVLNota")
        #-------------------------------------------------------------------
        self.retranslateUi(visualizar_aluno)
        QtCore.QMetaObject.connectSlotsByName(visualizar_aluno)

    def retranslateUi(self, visualizar_aluno):
        _translate = QtCore.QCoreApplication.translate
        visualizar_aluno.setWindowTitle(_translate("visualizar_aluno", "QT-Academico"))
        self.pushButton_procurar.setText(_translate("visualizar_aluno", "Procurar"))
        self.pushButton_voltar.setText(_translate("visualizar_aluno", "Voltar"))
        self.label.setText(_translate("visualizar_aluno", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Matricula:</span></p></body></html>"))
        self.groupBox.setTitle(_translate("visualizar_aluno", "Dados pessoais"))
        self.label_2.setText(_translate("visualizar_aluno", "Nome:"))
        self.label_3.setText(_translate("visualizar_aluno", "Matricula:"))
        self.label_4.setText(_translate("visualizar_aluno", "Idade:"))
        self.Label_SetMatricula.setText(_translate("visualizar_aluno", "Matricula"))
        self.Label_SetNome.setText(_translate("visualizar_aluno", "Nome"))
        self.Label_SetIdade.setText(_translate("visualizar_aluno", "Idade"))
        self.groupBox_2.setTitle(_translate("visualizar_aluno", "Médias finais:"))
        self.label_5.setText(_translate("visualizar_aluno", "Introdução a computação:"))
        self.label_6.setText(_translate("visualizar_aluno", "Introdução a programação:"))
        self.label_7.setText(_translate("visualizar_aluno", "Matemática discreta:"))
        self.label_8.setText(_translate("visualizar_aluno", "Cálculo I:"))
        self.label_9.setText(_translate("visualizar_aluno", "Algebra vetorial Linar:"))
        self.Label_ICNota.setText(_translate("visualizar_aluno", "Nota"))
        self.Label_IPNota.setText(_translate("visualizar_aluno", "Nota"))
        self.Label_MDNota.setText(_translate("visualizar_aluno", "Nota"))
        self.Label_CINota.setText(_translate("visualizar_aluno", "Nota"))
        self.Label_AVLNota.setText(_translate("visualizar_aluno", "Nota"))

class Ui_cadastrar_aluno(object):
    def setupUi(self, cadastrar_aluno):
        cadastrar_aluno.setObjectName("cadastrar_aluno")
        cadastrar_aluno.resize(311, 456)
        self.groupBox = QtWidgets.QGroupBox(cadastrar_aluno)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 271, 131))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(181, 255, 251);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setObjectName("label")
        self.lineEdit_getMatricula = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_getMatricula.setGeometry(QtCore.QRect(120, 30, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        #------------------------------------------------------------------------
        self.lineEdit_getMatricula.setFont(font)
        self.lineEdit_getMatricula.setObjectName("lineEdit_getMatricula")
        #------------------------------------------------------------------------
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(181, 255, 251);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setObjectName("label_2")
        self.lineEdit_getNome = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_getNome.setGeometry(QtCore.QRect(120, 60, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        #------------------------------------------------------------------------
        self.lineEdit_getNome.setFont(font)
        self.lineEdit_getNome.setText("")
        self.lineEdit_getNome.setObjectName("lineEdit_getNome")
        #------------------------------------------------------------------------
        self.lineEdit_getIdade = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_getIdade.setGeometry(QtCore.QRect(120, 90, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        #------------------------------------------------------------------------
        self.lineEdit_getIdade.setFont(font)
        self.lineEdit_getIdade.setText("")
        self.lineEdit_getIdade.setObjectName("lineEdit_getIdade")
        #------------------------------------------------------------------------
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(181, 255, 251);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(cadastrar_aluno)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 210, 271, 191))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_getICNota = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_getICNota.setGeometry(QtCore.QRect(190, 30, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        #------------------------------------------------------------------------
        self.lineEdit_getICNota.setFont(font)
        self.lineEdit_getICNota.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_getICNota.setObjectName("lineEdit_getICNota")
        #------------------------------------------------------------------------
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(181, 255, 251);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(181, 255, 251);")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setObjectName("label_5")
        self.lineEdit_getMDNota = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_getMDNota.setGeometry(QtCore.QRect(190, 90, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        #------------------------------------------------------------------------
        self.lineEdit_getMDNota.setFont(font)
        self.lineEdit_getMDNota.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_getMDNota.setObjectName("lineEdit_getMDNota")
        #------------------------------------------------------------------------
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(181, 255, 251);")
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setObjectName("label_6")
        self.lineEdit_getIPNota = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_getIPNota.setGeometry(QtCore.QRect(190, 60, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        #------------------------------------------------------------------------
        self.lineEdit_getIPNota.setFont(font)
        self.lineEdit_getIPNota.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_getIPNota.setObjectName("lineEdit_getIPNota")
        #------------------------------------------------------------------------
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 150, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(181, 255, 251);")
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(181, 255, 251);")
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_8.setObjectName("label_8")
        self.lineEdit_getCINota = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_getCINota.setGeometry(QtCore.QRect(190, 120, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        #------------------------------------------------------------------------
        self.lineEdit_getCINota.setFont(font)
        self.lineEdit_getCINota.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_getCINota.setObjectName("lineEdit_getCINota")
        #------------------------------------------------------------------------
        self.lineEdit_getAVLNota = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_getAVLNota.setGeometry(QtCore.QRect(190, 150, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        #------------------------------------------------------------------------
        self.lineEdit_getAVLNota.setFont(font)
        self.lineEdit_getAVLNota.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_getAVLNota.setObjectName("lineEdit_getAVLNota")
        #------------------------------------------------------------------------
        self.lineEdit_getTurma = QtWidgets.QLineEdit(cadastrar_aluno)
        self.lineEdit_getTurma.setGeometry(QtCore.QRect(150, 30, 141, 20))
        self.lineEdit_getTurma.setObjectName("lineEdit_getTurma")
        #------------------------------------------------------------------------
        self.label_9 = QtWidgets.QLabel(cadastrar_aluno)
        self.label_9.setGeometry(QtCore.QRect(20, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        #------------------------------------------------------------------------
        self.pushButton_ADD = QtWidgets.QPushButton(cadastrar_aluno)
        self.pushButton_ADD.setGeometry(QtCore.QRect(20, 420, 75, 23))
        self.pushButton_ADD.setObjectName("pushButton_ADD")
        self.pushButton_ADD.clicked.connect(cadas_aluno)
        #------------------------------------------------------------------------
        self.pushButton_Voltar = QtWidgets.QPushButton(cadastrar_aluno)
        self.pushButton_Voltar.setGeometry(QtCore.QRect(220, 420, 75, 23))
        self.pushButton_Voltar.setObjectName("pushButton_Voltar")
        self.pushButton_Voltar.clicked.connect(Window_MM)
        #------------------------------------------------------------------------
        self.retranslateUi(cadastrar_aluno)
        QtCore.QMetaObject.connectSlotsByName(cadastrar_aluno)

    def retranslateUi(self, cadastrar_aluno):
        _translate = QtCore.QCoreApplication.translate
        cadastrar_aluno.setWindowTitle(_translate("cadastrar_aluno", "QT-Academico"))
        self.groupBox.setTitle(_translate("cadastrar_aluno", "Dados Pessoais"))
        self.label.setText(_translate("cadastrar_aluno", "Matricula:"))
        self.label_2.setText(_translate("cadastrar_aluno", "Nome:"))
        self.label_3.setText(_translate("cadastrar_aluno", "Idade:"))
        self.groupBox_2.setTitle(_translate("cadastrar_aluno", "Médias semestrais"))
        self.label_4.setText(_translate("cadastrar_aluno", "Introdução a computação:"))
        self.label_5.setText(_translate("cadastrar_aluno", "Introdução a programação:"))
        self.label_6.setText(_translate("cadastrar_aluno", "Matemática discreta:"))
        self.label_7.setText(_translate("cadastrar_aluno", "Algebra vetorial linear:"))
        self.label_8.setText(_translate("cadastrar_aluno", "Cálculo I:"))
        self.label_9.setText(_translate("cadastrar_aluno", "Nome da turma:"))
        self.pushButton_ADD.setText(_translate("cadastrar_aluno", "Adicionar"))
        self.pushButton_Voltar.setText(_translate("cadastrar_aluno", "Voltar"))   


#######Janela principal######
app_Main = QtWidgets.QApplication(sys.argv)
Menu_Main = QtWidgets.QMainWindow()
ui_Main = Ui_Menu()
ui_Main.setupUi(Menu_Main)
#######Janela de nova turma#####
Menu_NT = QtWidgets.QWidget()
ui_NT = Ui_Frame_Nova_turma()
ui_NT.setupUi(Menu_NT)
######Janela carregar turma####
Menu_CT = QtWidgets.QWidget()
ui_CT = Ui_Frame_carregar_turma()
ui_CT.setupUi(Menu_CT)
######Janela de visualizar dados######
visualizar_aluno = QtWidgets.QWidget()
ui_VD = Ui_visualizar_aluno()
ui_VD.setupUi(visualizar_aluno)
#######Janela de cadastrar aluno####
cadastro_aluno = QtWidgets.QWidget()
ui_CD = Ui_cadastrar_aluno()
ui_CD.setupUi(cadastro_aluno)
#######Execução#############
Window_MM()
app_Main.exec_()